feat: page name for welcome page
radicle-dev/drips-app-v2 pull request #104
Opened 2022-11-17 14:30 UTC by efstajas

2022-11-17 17:26 UTC, evvvritt requested changes
@lftherios - do you have thoughts on meta/social Title and Description?

I was thinking the following:
**Drips**
**An Ethereum protocol for streaming and splitting funds, built by Radicle.**

or should Radicle be in the Title always?
**Radicle Drips**
**Drips by Radicle**

cc @brandonhaslegs

2022-11-17 17:26 UTC, evvvritt commented on src/routes/+page.svelte
> +  <title>Radicle Drips</title>
Drips

2022-11-17 17:26 UTC, evvvritt commented on src/routes/app/+page.svelte
> +  <title>Radicle Drips - Welcome</title>
Welcome – Drips

2022-11-18 10:27 UTC, brandonhaslegs commented
Why we welcoming someone to the website? seems very 2001 welcome to my homepage i'm a webmaster to me.

2022-11-18 10:28 UTC, efstajas commented
> Why we welcoming someone to the website? seems very 2001 like "welcome to my homepage i'm the webmaster".

what should we call the page instead?

2022-11-18 10:37 UTC, lftherios commented
> @lftherios - do you have thoughts on meta/social Title and Description?
> 
> I was thinking the following: **Drips** **An Ethereum protocol for streaming and splitting funds, built by Radicle.**

Yeah that's perfect!

2022-11-18 10:44 UTC, brandonhaslegs commented
> what should we call the page instead?

Just `Radicle Drips`, or just `Drips` on the first page. When visiting another page, you can just append the page name to that with a `|` or a `•` between.

2022-11-18 11:29 UTC, efstajas commented
I'd just argue that the page name is more important than `Drips` on nested pages, also imo just `Drips` is too short of a title for the landing page considering that it'll be indexed with that on Google. How about this:

```
- /: `Drips • Stream and Split Funds on Ethereum`
  - /app: `Drips`
    - /[userId]: `< user ID / ens > | Drips`
      - /[tokenAddress]: `< token name >  | Drips`
        - /[streamId]: `< stream name >  | Drips`
    - /dashboard: `Dashboard | Drips`
    - /settings: `Settings | Drips`
```

2022-11-18 13:30 UTC, brandonhaslegs approved these changes

2022-11-18 14:39 UTC, evvvritt requested changes
change all titles to just "Drips"
otherwise it's redundant with description which appears with title on Google, social etc...
simpler + sexier!

2022-12-01 13:10 UTC, efstajas commented
@evvvritt Adjusted title for sharing on twitter etc. but kept same for Google, as discussed in the design chat 👍

2022-12-01 14:57 UTC, evvvritt approved these changes

2022-12-01 15:17 UTC, merged