Feat: Squeezing
radicle-dev/drips-app-v2 pull request #285
Opened 2023-01-23 11:39 UTC by efstajas

2023-01-23 14:13 UTC, efstajas commented
Docs PR: https://github.com/radicle-dev/radicle-drips-docs/pull/10

2023-01-23 17:22 UTC, evvvritt commented on src/lib/flows/collect-flow/collect-amounts.svelte
> +        The amounts shown below are estimated based on your system time, and the value you actually
```suggestion
        The amounts shown below are estimated based on your system time so the value you 
```

2023-01-23 17:26 UTC, evvvritt requested changes
nice start!! some things:
(1. discussed tx error when splits exist)
2. awkward animation:
<img width="1184" alt="Screen Shot 2023-01-23 at 17 39 22" src="https://user-images.githubusercontent.com/6071219/214107536-d1f732ab-4457-4de1-be73-7da8885451c7.png">

2023-01-24 09:10 UTC, efstajas commented
> 2. awkward animation

Fixed that, waiting for squeezing fix 👍

2023-01-24 10:50 UTC, efstajas commented
@evvvritt SDK updated, splitting fixed 👌

2023-01-24 12:43 UTC, evvvritt approved these changes
approved!
one last thing would be improve this success panel on mobile.
maybe "...your wallet address." and link to the etherscan tx? (omitt address)
or css break-all on address string, or use the abbreviated address component
<img width="474" alt="Screen Shot 2023-01-24 at 13 41 28" src="https://user-images.githubusercontent.com/6071219/214294617-5602e2c5-66eb-46d9-9de3-e68dd6950ed7.png">

2023-01-24 14:05 UTC, merged